on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install .
      - name: Clone Nebula Docker Compose
        run: git clone https://github.com/vesoft-inc/nebula-docker-compose.git
      - name: Run Docker Compose
        run: |
          cd nebula-docker-compose
          docker compose -f docker-compose-lite.yaml up -d
      - name: Wait for NebulaGraph to be ready
        run: sleep 20s
      - name: Load initial data
        run: |
          docker run --rm --network host vesoft/nebula-console:nightly -addr 127.0.0.1 -port 9669 -u root -p nebula -e ":play basketballplayer"
      - name: Run tests
        run: pytest
